export const softwareCapabilities = [
  "Systems design & specification",
  "Software programming",
  "Real-time applications",
  "Process control",
  "Data communications",
  "Automated test equipment (ATE)",
  "Verification & validation",
  "Process automation",
  "Real-time systems",
  "Test plans & test documentation",
];

export const hardwareCapabilities = [
  "Feasibility studies",
  "Circuit design",
  "Product specification (features & function)",
  "Optical design",
  "Printed circuit layout & documentation (PCAD)",
  "Prototyping & bring-up",
  "Production engineering & documentation",
  "Value engineering",
  "Special test equipment",
  "Competitive product analysis",
  "Printed circuit board (PCB) CAD",
  "Manufacturing support & DFM",
  "FPGA / ASIC design feasibility studies",
  "Logic & interface design",
  "Automation (lab & line)",
  "Automated testing",
  "Mechanical CAD integration",
  "Data communication & buses",
  "Control systems",
  "RS-422, RS-232, RS-485 communications",
];

export const languagesAndTools = [
  "C / C++ (firmware, drivers, services)",
  "Assembly languages (MCU-specific)",
  "COM / DCOM",
  "Ethernet stacks & lab tooling",
  "LabVIEW / LabWindows",
  "Linux toolchain & embedded Linux bring-up",
  "Microchip PIC ecosystem",
  "MFC & classic Windows tooling (maintenance)",
  "Perl & scripting for automation",
  "RTOS & bare-metal environments",
  "TCP/IP software & network bring-up",
  "Unix / POSIX toolchains",
  "Visual Basic & ActiveX (legacy systems)",
  "Microsoft Windows engineering tools",
];
